### Exercise

In [1]:
import numpy as np 

In [3]:
#### Valid Sudoko

In [4]:
sudoku = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [5]:
b= np.sum(sudoku, axis=1)
for i in b:
    if i != 45:
        print("sudoku is not valid")
        break
else:
        print("for rows it is valid")
    

for rows it is valid


In [6]:
c = np.sum(sudoku, axis  = 0)
for i in c:
    if i != 45:
        print("sudoku is not valid")
        break
else:
        print("for columns it is valid")
    

for columns it is valid


In [8]:
sudoku[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [9]:
sudoku[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [10]:
sudoku[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [11]:
for rows in range(0,9,3):
    for columns in range(0,9,3):
        n=sudoku[rows:rows+3,columns:columns+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [41]:
#  Columns : (Age , Maths Marks, Science Marks )
# Students
data = np.array([
    [18, 85, 78],
    [19, 92, 88],
    [17, 76, 95],
    [18, 65, 70],
    [20, 90, 85]
])
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [13]:
#Get the shape of the matrix.
#Find the average age of students.
#Extract Math marks of all students.
#Find the highest Science mark.





In [14]:
data.shape

(5, 3)

In [15]:
age = data[0:,:1]
age

array([[18],
       [19],
       [17],
       [18],
       [20]])

In [16]:
age.mean()

np.float64(18.4)

In [17]:
math_marks = data[0:,1:2]
math_marks

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [18]:
science_marks = data[0:,2:].max()
science_marks

np.int64(95)

In [19]:
#Get details of the student who scored more than 90 in Math.
math_marks[math_marks > 90]

array([92])

In [21]:
#Increase Math marks of all students by 5.
new_math_marks = math_marks + 5
new_math_marks

array([[90],
       [97],
       [81],
       [70],
       [95]])

In [23]:
#Find how many students are younger than 19.
ages = data[0:,:1]
ages[ages<19]

array([18, 17, 18])

In [29]:
#Calculate the average marks in each subject (column-wise mean).


data[0:,1:].mean(axis =0)
np.mean(data[0:,1:],axis = 0) # Both are same 

array([81.6, 83.2])

In [33]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,2] >=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [43]:
#Replace all Science marks < 75 with 0.
data[0:,2:][data[0:,2:] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])