In [1]:
import numpy as np 

#### Basic array creation

In [2]:
arr1 = np.array([1,2,3,4])

In [3]:
arr1

array([1, 2, 3, 4])

In [6]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
arr2 = np.array(l) # 2d array
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
# array creation by built in 

In [13]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,3)) # Zeros array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((3,4)) # array of one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.linspace(1,5,2)
np.linspace(1,10,9) # linear space between every element , start and end given by us , and its the range 

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

#### Random Generation function

In [23]:
np.random.rand(5) # give random element 

array([0.27497051, 0.72858636, 0.26834731, 0.92945905, 0.13024871])

In [25]:
np.random.randn(15)

array([ 0.31514038,  1.61146884,  0.44666682,  0.82900036,  1.87230718,
        0.05119625,  0.56058989,  0.403729  , -0.62853588,  0.39654921,
       -1.17886174, -0.20633701, -0.96675712, -0.25711177,  0.39179253])

In [29]:
np.random.randint(6) # give random number between zero to 6 or given element 

4

In [32]:
np.random.randint(1,20,10) # here i give range and elements count,

array([16,  7,  9,  4,  2, 13, 19,  8,  7, 11], dtype=int32)

#### Array Attributes 

In [33]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [34]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr.shape

(3, 3)

In [36]:
arr.size

9

In [37]:
arr.dtype

dtype('int64')

#### Array Methods

In [38]:
arr.min()

np.int64(1)

In [39]:
arr.max()

np.int64(9)

In [40]:
arr.sum() # sum of all elements

np.int64(45)

In [41]:
np.sum(arr, axis = 0) # column wise sum

array([12, 15, 18])

In [42]:
np.sum(arr, axis = 1) # row wise sum 

array([ 6, 15, 24])

In [44]:
arr.mean()

np.float64(5.0)

In [45]:
arr.std()

np.float64(2.581988897471611)

In [46]:
arr.argmax()

np.int64(8)

In [48]:
arr.argmin()

np.int64(0)

#### Reshaping and Resizing

In [50]:
array = np.arange(1,31)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [55]:
arr1 = array.reshape(2,15)
arr2 = array.reshape(3,10)
arr3 = array.reshape(5,6)
arr4 = array.reshape(6,5)
arr6 = array.reshape(10,3)
arr5 = array.reshape(2,15)
arr1


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [56]:
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [57]:
arr3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [58]:
arr4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [59]:
arr5

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [60]:
arr6

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [61]:
array = arr6 # size change

In [62]:
array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])