In [1]:
import numpy as np 

#### Numpy indexing and slicing of vectors

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[6] # print the elements

np.int64(17)

In [4]:
arr[1:5] # slicing of an array  
arr[:5] 
arr[3:]
# 1st and last is already imagine if it is not given

array([14, 15, 16, 17, 18, 19, 20])

#### Numpy indexing and slicing of Matrix 

In [5]:
array = np.arange(1,31)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [6]:
arr = array.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

arr[4,3]

In [7]:
arr[5,4]

np.int64(30)

In [8]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [9]:
slice = arr[3:6,3:5]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

## Array operations

#### Arithmetic operations

In [10]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [11]:
a1 + a2 

array([ 7,  9, 11, 13, 15])

In [12]:
a2-a1

array([5, 5, 5, 5, 5])

In [13]:
a1*a2 

array([ 6, 14, 24, 36, 50])

In [14]:
a2/a1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [15]:
a2//a1

array([6, 3, 2, 2, 2])

In [16]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

#### Broadcasting

In [17]:
l=[10,20,30,40]
arr = np.array(l)

In [18]:
arr

array([10, 20, 30, 40])

In [19]:
arr +10

array([20, 30, 40, 50])

In [46]:
# Deep and shallow copy

In [20]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
slice = a[:5] # shallow copy 
slice

array([1, 2, 3, 4, 5])

In [22]:
slice = slice * 10 # shallow copy 
slice

array([10, 20, 30, 40, 50])

In [23]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
arr1 = a[4:6] * 10
arr1

array([50, 60])

In [25]:
a 
b=a  # deep copy  

In [26]:
b[0] = 99 # deep copy 
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

#### matrix Operations 

In [36]:
mat1 = np.array([[1,2],[4,5]])
mat2 = np.array([[1,2],[4,5]])


In [37]:
mat1

array([[1, 2],
       [4, 5]])

In [38]:
mat2

array([[1, 2],
       [4, 5]])

In [39]:
mat1*mat2

array([[ 1,  4],
       [16, 25]])

#### stacking array 

In [40]:
a1 = np.array([1,2,4,5])
a2 = np.array([1,2,4,5])

In [41]:
a1

array([1, 2, 4, 5])

In [42]:
a2

array([1, 2, 4, 5])

In [43]:
np.stack((a1,a2))

array([[1, 2, 4, 5],
       [1, 2, 4, 5]])

In [44]:
np.hstack((a1,a2))

array([1, 2, 4, 5, 1, 2, 4, 5])

In [45]:
np.column_stack((a1,a2))

array([[1, 1],
       [2, 2],
       [4, 4],
       [5, 5]])